name: Linux packages

on: [push, pull_request]

env:
  PACKAGE_NAME: libpcut
  PACKAGE_MAINTAINER: vhotspur
  PACKAGE_DESCRIPTION: "Plain C unit testing framework"
  PACKAGE_VERSION: 0.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Select compiler and build type
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release --install-prefix=/usr

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Install
        env:
          DESTDIR: ${{github.workspace}}/pkg
        run: cmake --install ${{github.workspace}}/build

      - uses: jiro4989/build-deb-action@v3
        with:
          package_root: ${{github.workspace}}/pkg
          package: ${{ env.PACKAGE_NAME }}
          maintainer: ${{ env.PACKAGE_MAINTAINER }}
          desc: '${{ env.PACKAGE_DESCRIPTION }}'
          version: '${{ env.PACKAGE_VERSION }}'
          arch: 'amd64'

      - uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: |
            ./*.deb

      - uses: jiro4989/build-rpm-action@v2
        with:
          package_root: ${{github.workspace}}/pkg
          package: ${{ env.PACKAGE_NAME }}
          maintainer: ${{ env.PACKAGE_MAINTAINER }}
          desc: '${{ env.PACKAGE_DESCRIPTION }}'
          version: '${{ env.PACKAGE_VERSION }}'
          arch: 'x86_64'

      - uses: actions/upload-artifact@v3
        with:
          name: rpm-package
          path: |
            ./*.rpm
