name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release --install-prefix=/usr

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Package
        working-directory: ${{github.workspace}}/build
        run: cpack -C ${{matrix.build_type}} -G "RPM;DEB" -B pkg

      - name: Upload built packages
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: build/pkg/pcut*
          retention-days: 1

  macos-packages:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Package
        working-directory: ${{github.workspace}}/build
        run: cpack -C ${{matrix.build_type}} -G "productbuild" -B pkg

      - name: Upload built packages
        uses: actions/upload-artifact@v4
        with:
          name: macos-packages
          path: build/pkg/pcut*
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: [linux-packages, macos-packages]
    steps:

      - name: Fetch Linux packages
        uses: actions/download-artifact@v4
        with:
          name: linux-packages
          path: pkg

      - name: Fetch MacOS packages
        uses: actions/download-artifact@v4
        with:
          name: macos-packages
          path: pkg

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: pkg/*
